logging:
  level:
    ROOT: INFO
    com.albedo.java: DEBUG
server:
  port: 8061
  servlet:
    session:
      timeout: 30m

spring:
  profiles:
    active: dev
    include:
      - swagger
  #      - jwt
  redis:
    password:
    host: localhost
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gavin
    password: g1126ang
    url: jdbc:mysql://47.100.1.162:3306/albedo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true


# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  adminPath: /a
  developMode: true
  security:
    remember-me:
      key: albedo-admin
    authentication:
      jwt:
        # 必须使用最少88位的Base64对该令牌进行编码
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    authorize-permit-all:
      - ${application.adminPath}/code/**
      - ${application.adminPath}/sys/user/register
      - ${application.adminPath}/biz/plan/list
      - ${application.adminPath}/tool/aliPay/notify
      - /cdn/*
      - /fonts/*
